/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Simple sidebar for the basic docs
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder
    },
  ],
};

module.exports = sidebars;
