/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    { type: 'autogenerated', dirName: '.' }
  ],
  smartContractSidebar: [
    { type: 'autogenerated', dirName: 'smart-contract' }
  ],
  apiSidebar: [
    { type: 'autogenerated', dirName: 'api' }
  ],
  frontEndSidebar: [
    { type: 'autogenerated', dirName: 'frontend' }
  ],
  qaSidebar: [
    { type: 'autogenerated', dirName: 'qa' }
  ],
  maintainerSidebar: [
    { type: 'autogenerated', dirName: 'maintainer' }
  ],
};

module.exports = sidebars;
